---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcs.saved.name}}
  labels:
      app: {{ include "palworld.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvcs.saved.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
---
{{- if .Values.backups.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcs.backups.name }}
  labels:
      app: {{ include "palworld.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvcs.backups.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcs.server.name }}
  labels:
      app: {{ include "palworld.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvcs.server.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
