---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
      app: {{ include "palworld.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvc.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
{{/*---*/}}
{{/*{{}}*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.pvc.name }}-backups*/}}
{{/*  labels:*/}}
{{/*      app: {{ include "palworld.name" . }}*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*spec:*/}}
{{/*    accessModes:*/}}
{{/*        - ReadWriteOnce*/}}
{{/*    resources:*/}}
{{/*        requests:*/}}
{{/*          storage: {{ .Values.pvc.size }}*/}}
{{/*    storageClassName: {{ .Values.storageClassName | default "longhorn" }}*/}}