apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalIPs:
    - {{ .Values.endpoint.externalIP }}
  ports:
    - port: {{ .Values.endpoint.queryPort }}
      targetPort: query
      protocol: UDP
      name: query
    - port: {{ .Values.endpoint.gamePort }}
      targetPort: game
      protocol: UDP
      name: game
  selector:
    {{- include "palworld.selectorLabels" . | nindent 4 }}
