apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enshrouded.fullname" . }}
  labels:
    {{- include "enshrouded.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "enshrouded.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "enshrouded.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enshrouded.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.backups.enabled }}
        - name: save-backups
          image: "mbround18/backup-cron:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SCHEDULE
              value: "{{ .Values.backups.schedule }}"
            - name: INPUT_FOLDER
              value: "/home/steam/enshrouded/savegame"
            - name: OUTPUT_FOLDER
              value: "/home/steam/backups/"
            - name: OUTPUT_USER
              value: "1000"
            - name: OUTPUT_GROUP
              value: "1000"
            - name: RETAIN_N_DAYS
              value: "{{ .Values.backups.retentionDays | default "7" }}"
            - name: FILES_TO_KEEP
              value: "{{ .Values.backups.filesToKeep | default "0" }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.environment }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{ range list "TCP" "UDP" }}
            {{- $game := printf "%s-%s" "game" . -}}
            {{- $query := printf "%s-%s" "query" . -}}
            - name: {{ lower $game }}
              containerPort: {{ $.Values.endpoint.gamePort }}
              protocol: {{ . }}
            - name: {{ lower $query }}
              containerPort: {{ $.Values.endpoint.queryPort }}
              protocol: {{ . }}
            {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
